config/routes.rb
Rails.application.routes.draw do
  root 'quiz#index'
  resources :planes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plane.rb
class Plane < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  def index
    @plane = Plane.last
  end

  def new
    @plane = Plane.new
  end

  def create
    Plane.create(plane_params)
    redirect_to planes_path
  end

  def show
  end
end



private

  def plane_params
    params.require(:plane).permit(:model, :description)
  end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planes/index.html.erb
<h1>Planes Go Here</h1>

<h1><%= @plane.model %></h1>
<h2>- <%= @plane.description %></h2>

app/views/planes/new.html.erb
<h1>Enter Your Plane Details</h1>
<%= simple_form_for @plane do |f| %>
  <%= f.input :model %>
  <%= f.input :description %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>

app/views/quiz/index.html.erb
<h1>I passed quiz 2</h1>

<%= link_to 'Add a Plane', new_plane_path %> 